src/Entity/File.php
<?php

namespace App\Entity;

use App\Repository\FileRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Uid\Uuid;

/**
 * @ORM\Entity(repositoryClass=FileRepository::class)
 */
class File
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", unique=true)
     */
    private $uuid;

    /**
     * @ORM\ManyToOne(targetEntity=Folder::class, inversedBy="contentsFiles")
     */
    private $folder;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * Localized or third party? (0 => Local upload, 1 => Outside URL)
     *
     * @ORM\Column(type="integer", length=255)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $url;

    public function __construct()
    {
        $this->uuid = Uuid::v4();
    }

    public function __toString()
    {
        if (is_null($this->getExtension())) {
            return $this->getName();
        }
        return $this->getName() . "." . $this->getExtension();
    }

    public function getExtension(): ?string
    {
        if (str_contains($this->getName(), "."))
        {
            $exp = explode(".", $this->getName());
            return array_pop($exp);
        }
        return null;
    }


    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFolder(): ?Folder
    {
        return $this->folder;
    }

    public function setFolder(?Folder $folder): self
    {
        $this->folder = $folder;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(?string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getUuid()
    {
        return $this->uuid;
    }

    public function setUuid($uuid)
    {
        $this->uuid = $uuid;

        return $this;
    }

}

src/Controller/FilesystemController.php
<?php

namespace App\Controller;

use App\Entity\File;
use App\Entity\Folder;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityManagerInterface;
use Exception;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * Class FilesystemController
 *
 * @package App\Controller
 */

class FilesystemController extends AbstractController
{

    /**
     * @var EntityManagerInterface $entityManager
     */
    private $entityManager;

    /**
     * FilesystemController constructor.
     *
     * @param EntityManagerInterface $em
     */
    public function __construct(EntityManagerInterface $em)
    {
        $this->entityManager = $em;
    }

    /**
     * Main view controller
     *
     * @param Request     $request
     * @param String|null $folder
     *
     * @return Response
     * @todo: Validate user has access to folder/file
     *
     * @Route("/", name="site_view")
     * @Route("/path/{folder}", name="site_view_folder")
     *
     */
    public function view(Request $request, $folder = null): Response
    {

        // Null means root ("/") is being requested. Generate root if no folder provided.
        if (is_null($folder)) {
            $folder = $this->_getRootFolder();
        } else {
            $folder = $this->getDoctrine()->getRepository(Folder::class)->findUuid($folder);
        }

        /**
         * @var Folder $folder
         */

        // Check that folder exists
        if (is_null($folder)) {
            return $this->render($request->isXmlHttpRequest() ? 'file_system/error_ajax.html.twig' : 'file_system/error.html.twig', [
                'user' => $this->getUser(),
                'type' => 404
            ]);
        }

        // Render template
        return $this->render($request->isXmlHttpRequest() ? 'file_system/view_ajax.html.twig' : 'file_system/view.html.twig', [
            'user' => $this->getUser(),
            'directory' => $folder->getPath(),
            'explorerTree' => $this->_getExplorerTree(clone $folder),
            'head' => $folder,

            // ternary > lambda [refactor this]
            // If folder is set, display said.
            'folder' => is_null($folder->getUuid()) ?
                $folder->getChildFolders()

                // If parent folder does not exist, display root folder
                : (is_null($folder->getParentFolder()) ?
                    [(clone $this->_getRootFolder())->setName(".."), ...$folder->getChildFolders()]

                    // Otherwise, display parent folder.
                    : [(clone $folder->getParentFolder())->setName(".."), ...$folder->getChildFolders()]
                ),
            'files' => $folder->getChildFiles()
        ]);
    }

    /**
     * Generate a Folder object for the root (/) location
     *
     * @return Folder
     */
    protected function _getRootFolder()
    {
        $folder = new Folder("");
        $folder->setUuid(null);

        // Grab all orphan folders
        foreach ($this->getDoctrine()->getRepository(Folder::class)->findBy(['parentFolder' => null]) as $f) {
            /* @var Folder $f */
            $folder->addContentsFolder($f);
        }

        // Grab all orphan files
        foreach ($this->getDoctrine()->getRepository(File::class)->findBy(['folder' => null]) as $f) {
            /* @var File $f */
            $folder->addContentsFile($f);
        }
        return $folder;

    }

    /**
     * Generate a tree structure based on the requested folder's location
     *
     * @param Folder $folder
     *
     * @return Folder
     * @todo: Verify user has access to folders/files mentioned in tree. Throw global error if un-allowed is found.
     *
     */
    protected function _getExplorerTree(Folder $folder)
    {

        // Nullfiy folder's second sublevel (children's children). Ensure that at least one iteration is completed
        $child = null;
        do {
            foreach ($folder->getChildFolders() as $sub) {
                if ($sub->getChildFolders()->count() > 0) {
                    $sub->hasChildren = true;
                }
                if ($sub->getUuid() !== $child) {
                    $sub->setChildFolders(new ArrayCollection());
                }

            }
            $child = $folder->getUuid();
            $folder = $folder->getParentFolder();
        } while ($folder != null);


        foreach ($this->_getRootFolder()->getChildFolders() as $sub) {
            if ($sub->getChildFolders()->count() > 0) {
                $sub->hasChildren = true;
            }
            if ($sub->getUuid() !== $child) {
                $sub->setChildFolders(new ArrayCollection());
            }
        }
        return $this->_getRootFolder();
    }

    /**
     * Explorer node controller
     *
     * @Route("/explorer/stem/{uuid}", name="ajax_explorer_stem")
     *
     * @param String $uuid
     *
     * @return Response
     */
    public function getExplorerNode($uuid = null)
    {
        // Null means root ("/") is being requested. Generate root if not provided.
        if (is_null($uuid)) {
            $folder = $this->_getRootFolder();
        } else {
            $folder = $this
                ->getDoctrine()
                ->getRepository(Folder::class)
                ->findUuid($uuid);
        }

        return $this->render("file_system/explorer_node.html.twig", [
            'folders' => $folder->getChildFolders()
        ]);
    }


}

templates/file_system/explorer.html.twig
{%- macro render(folders, recursive) -%}
    {%- if folders|length > 0 -%}
        <ul class="section">
            {%- for i in folders -%}
                <li data-uuid="{{ i.uuid }}">
                    <div class="explorer-item-bar">
                        {%- if i.hasChildFolders() or i.hasChildren -%}
                            <svg class="explorer-caret{% if i.hasChildFolders() and recursive %} explorer-extended{% endif %}"
                                 width="16px"
                                 height="16px"
                                 viewBox="0 0 24 24"
                                 fill="none"
                                 data-uuid="{{ i.uuid }}"
                                 data-url="{{ url('ajax_explorer_stem', {uuid: i.uuid}) }}"
                                 xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" clip-rule="evenodd"
                                      d="M9.96967 7.46967C10.2626 7.17678 10.7374 7.17678 11.0303 7.46967L15.0303 11.4697C15.3232 11.7626 15.3232 12.2374 15.0303 12.5303L11.0303 16.5303C10.7374 16.8232 10.2626 16.8232 9.96967 16.5303C9.67678 16.2374 9.67678 15.7626 9.96967 15.4697L13.4393 12L9.96967 8.53033C9.67678 8.23744 9.67678 7.76256 9.96967 7.46967Z"/>
                            </svg>

                        {%- else -%}
                            <svg width="16px" height="16px" viewBox="0 0 24 24" fill="none"
                                 xmlns="http://www.w3.org/2000/svg">
                            </svg>
                        {%- endif -%}
                        <div class="explorer-item-title">
                            <a
                                    data-ajax="true"
                                    data-ajax-target="target-ajax"
                                    href="{% if i.url is defined %}{{ i.url }}{% else %}{{ url('site_view_folder', {folder: i.uuid}) }}{% endif %}"
                                    title="{{ i.name }}">
                                <img width="16px" src="{{ asset("build/images/icons/folder.svg") }}"/> {{ i.name }}
                            </a>
                        </div>
                    </div>
                    <div class="explorer-item-contents">
                        {%- if recursive -%}
                            {%- import _self as self -%}
                            {{- self.render(i.getChildFolders(), true) -}}
                        {%- endif -%}
                    </div>
                </li>
            {%- endfor -%}
        </ul>
    {%- endif -%}
{%- endmacro -%}

templates/file_system/explorer_node.html.twig
{% import "file_system/explorer.html.twig" as explorer %}
{{ explorer.render(folders, false) }}

templates/file_system/file_card.html.twig
<span data-contextmenu="true"
      data-contextmenu-uuid="{{ child.getUuid() }}"
      data-contextmenu-baseurl="{{ url('site_view') }}">

    <a class="card bg-hover"
       data-uuid="{{ child.uuid }}"
       data-local="{% if child.type == 0 %}true{% else %}false{% endif %}"
       href="{{ child.url }}"
       target="_blank"
       title="{{ child.name }}">

        <div>
            <img class="icon"
                 src="{% if file_exists("build/images/icons/#{child.extension|lower}.svg") %}{{ asset("build/images/icons/#{child.extension|lower}.svg") }}{% else %}{{ asset("build/images/icons/_default.svg") }}{% endif %}"/>
        </div>
        <div class="name">{{ child.name }}</div>


    </a>

    <div class="contextmenu hidden">
        <ul>
            <li data-contextmenu-action="null"
            ><a href="{{ child.url }}" target="_blank">View</a></li>

            {# Must be logged in to modify items #}
            {% if is_granted("ROLE_ADMIN") and child.uuid|length > 0 %}
                <li data-contextmenu-action="popup"
                    data-contextmenu-title="Rename File"
                    data-contextmenu-href="{{ url('site_file_rename', {uuid: child.uuid}) }}"
                >Rename</li>

                <li data-contextmenu-action="popup"
                    data-contextmenu-title="Move File"
                    data-contextmenu-href="{{ url('site_file_move', {uuid: child.uuid}) }}"
                >Move</li>

                <li class="danger"
                    data-contextmenu-action="popup-confirm"
                    data-contextmenu-title="Delete File"
                    data-contextmenu-href="{{ url('site_file_delete', {uuid: child.uuid}) }}"
                >Delete</li>
            {% endif %}
        </ul>
    </div>

</span>

templates/file_system/folder_card.html.twig
<span data-contextmenu="true"
      data-contextmenu-uuid="{{ child.getUuid() }}"
      data-contextmenu-baseurl="{{ url('site_view') }}">

    <a class="card bg-hover"
       data-uuid="{{ child.uuid }}"
       data-ajax="true"
       data-ajax-target="target-ajax"
       href="{{ url('site_view_folder', {folder: child.uuid}) }}"
       title="{{ child.name }}">

        <div>
            <img class="icon"
                 src="{{ asset("build/images/icons/folder.svg") }}"/>
        </div>
        <div class="name">{{ child.name }}</div>


    </a>

    <div class="contextmenu hidden">
        <ul>
            <li data-contextmenu-action="null"
                data-ajax="true"
                data-ajax-target="target-ajax"
                href="{% if child.url is defined %}{{ child.url }}{% else %}{{ url('site_view_folder', {folder: child.uuid}) }}{% endif %}"
            >View</li>

            {# Must be logged in to modify items #}
            {% if is_granted("ROLE_ADMIN") and child.uuid|length > 0 %}
                <li data-contextmenu-action="popup"
                    data-contextmenu-title="Rename Folder"
                    data-contextmenu-href="{{ url('site_folder_rename', {uuid: child.uuid}) }}"
                >Rename</li>

                <li data-contextmenu-action="popup"
                    data-contextmenu-title="Move Folder"
                    data-contextmenu-href="{{ url('site_folder_move', {uuid: child.uuid}) }}"
                >Move</li>

                <li class="danger"
                    data-contextmenu-action="popup-confirm"
                    data-contextmenu-title="Delete Folder"
                    data-contextmenu-href="{{ url('site_folder_delete', {uuid: child.uuid}) }}"
                >Delete</li>
            {% endif %}
        </ul>
    </div>

</span>

templates/file_system/folder_not_authorized.html.twig
{% extends 'base.html.twig' %}

{% block title %}Error{% endblock %}

{% block body %}
    You do not have access to this folder!<br>
{% endblock %}

templates/file_system/folder_not_found.html.twig
{% extends 'base.html.twig' %}

{% block title %}Error{% endblock %}

{% block body %}
    This folder does not exist!<br>
{% endblock %}

templates/file_system/header.html.twig
{# Check if root "/" is parent. If not, show the hash for the file above ."Go up" #}

<div class="header-title">{{ directory }}</div>

{% if is_granted("ROLE_ADMIN") %}
    <nav class="navbar navbar-expand-lg navbar-light p">
        <ul class="navbar-nav mr-auto">

            <li class="nav-item m-1">
                <a id="add-folder"
                   class="nav-link nav-icon bg-hover"
                   data-popup="true"
                   data-popup-title="Add Folder"
                   data-popup-url="{{ url('site_folder_add', {parentUuid: head.getUuid()}) }}">
                    <img width="20px" height="20px" src="{{ asset("build/images/ui/folder-add.svg") }}"/>
                </a>
            </li>

            <li class="nav-item m-1">
                <a id="add-file"
                   class="nav-link nav-icon bg-hover"
                   data-popup="true"
                   data-popup-title="Add File"
                   data-popup-url="{{ url('site_file_add', {parentUuid: head.getUuid()}) }}">
                    <img width="20px" height="20px" src="{{ asset("build/images/ui/file-add.svg") }}"/>
                </a>
            </li>

        </ul>
    </nav>
{% endif %}

templates/file_system/item_card.html.twig
<span data-contextmenu="true"
      data-contextmenu-action="{% if (child.extension is defined) and (child.url is defined) %}file{% else %}folder{% endif %}"
      data-contextmenu-uuid="{{ child.getUuid() }}"
      data-contextmenu-baseurl="{{ url('site_view') }}">

    <div class="card bg-hover"
         data-ajax="true"
         data-ajax-target="target-ajax"
         href="{% if child.url is defined %}{{ child.url }}{% else %}{{ url('site_view_folder', {folder: child.uuid}) }}{% endif %}"
         title="{{ child.name }}{% if (child.extension is defined) and (child.url is defined) %}.{{ child.extension }}{% endif %}">

        <div>
            <img class="icon"
                 src="{% if file_exists("build/images/icons/#{child.extension}.svg") %}{{ asset("build/images/icons/#{child.extension}.svg") }}{% else %}{{ asset("build/images/icons/_default.svg") }}{% endif %}"/>
        </div>
        <div class="name">{{ child.name }}</div>


    </div>

    <div class="contextmenu hidden">
        <ul>
            <li data-contextmenu-action="null"
                data-ajax="true"
                data-ajax-target="target-ajax"
                href="{% if child.url is defined %}{{ child.url }}{% else %}{{ url('site_view_folder', {folder: child.uuid}) }}{% endif %}"
            >View</li>

            {% if is_granted("ROLE_ADMIN") and child.uuid|length > 0 %}
                <li data-contextmenu-action="popup"
                    data-contextmenu-title="Rename File"
                    data-contextmenu-href="{{ url('site_folder_rename', {uuid: child.uuid}) }}"
                >Rename</li>

                <li data-contextmenu-action="popup"
                    data-contextmenu-title="Move File"
                    data-contextmenu-href="{{ url('site_folder_move', {uuid: child.uuid}) }}"
                >Move</li>

                <li class="danger"
                    data-contextmenu-action="popup-confirm"
                    data-contextmenu-title="Delete File"
                    data-contextmenu-href="{{ url('site_folder_delete', {uuid: child.uuid}) }}"
                >Delete</li>
            {% endif %}
        </ul>
    </div>

</span>

templates/file_system/view.html.twig
{% extends 'base.html.twig' %}

{% block title %}Folder{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('site_view') }}
{% endblock %}

{% block body %}
    <div class="sidebar-wrapper">
        <div class="sidebar">
            <div class="brand">Files</div>
            <div class="explorer-container">
                {% import "file_system/explorer.html.twig" as explorer %}
                {{ explorer.render([explorerTree], true) }}
            </div>
        </div>
        {% if app.user is not null %}
            <div class="btn-group dropup user-block">
                <p class="dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                    {{ app.user.email }}
                </p>
                <ul class="dropdown-menu">
                    <div class="text-left">
                        <i class="fas fa-sign-out-alt"></i> <a href="{{ url('app_logout') }}">Log Out</a>
                    </div>
                </ul>
            </div>
        {% else %}
            <div class="user-block" id="login-popup">
                <a id="login"
                   data-popup="true"
                   data-popup-title="Login"
                   data-popup-url="{{ url('app_login') }}">Login</a>
            </div>
        {% endif %}
    </div>

    <div class="content-wrapper">

        <div class="target-ajax">
            {% include "file_system/view_ajax.html.twig" %}
        </div>

        {% include "file_system/footer.html.twig" %}
    </div>

    <a href="https://github.com/kaminskia1/filesystem">
        <i class="fab fa-github github"></i>
    </a>

{% endblock %}

templates/file_system/view_ajax.html.twig
<div class="content-top">
    {% include "file_system/header.html.twig" %}
</div>
<div class="content item-wrapper">
    {% for child in folder %}
        {% include "file_system/folder_card.html.twig" %}
    {% endfor %}
    {% for child in files %}
        {% include "file_system/file_card.html.twig" %}
    {% endfor %}
</div>